name: Deploy to Server

on:
    push: # you can remove unused branch names
        branches:
            - 'main'

jobs:
    # build the source code
    build:
        name: Build and push
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: build
              run: |
                  yarn
                  yarn build
            - name: push to production
              uses: cpina/github-action-push-to-another-repository@master
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source-directory: 'build'
                  destination-github-username: 'PlasmNetwork'
                  destination-repository-name: 'astar-faucet-bot'
                  user-email: devops@stake.co.jp
                  target-branch: 'deploy'
